git-touch/git-touch

lib/screens/gh_issue.dart, lib/widgets/timeline_item.dart
update `SubscribedEvent`, `MentionedEvent` and `PinnedEvent` timeline items in issues page.
=> update timeline event handlers in issues page

lib/screens/gh_search.dart
Just caught this. The border edges of the search bar were white in colour for the dark mode.
=> fix white edge color search bar on dark theme

lib/screens/gh_user.dart
Fixes #38. I aligned it centre. Let me know if you'd prefer it to be aligned left.
=> align contribution graph center for ipad

lib/widgets/repo_header.dart
Minor fix of overflow in Repo Header.
=> [fix] repo header text overflow

lib/home.dart
Fixes #57 and #54 
- I could not use a list as for some reason indexing with a list did not work. The state was always at `null`. Instead had to use five variables and reused them for all the platforms.
- Added a controller for the `CupertinoTabScaffold` as I need to get the value of `index` in `onWillPop`. I initially used a temporary variable and updated its value each time a tab bar item was clicked but because of using `await` in `onWillPop` it created trouble. And a controller inherently seems like a better option.
Let me know if there are any changes to be made. Thanks!
=> fix: back button android, return home on tap

lib/models/auth.dart
=> fix: error using same token 

lib/models/github.dart, lib/models/github.g.dart, lib/router.dart, lib/screens/gh_compare.dart, lib/widgets/event_item.dart
- Looks like the Files screen.
- Included the share options as suggested last time while implementing `GhFilesScreen`
@pd4d10 Let me know if there are any changes to be made. Thanks.
=> feat: github compare screen

lib/router.dart, lib/screens/gh_commits.dart, lib/screens/gh_compare.dart, lib/screens/gh_contributors.dart, lib/screens/gh_issue.dart, lib/screens/gh_issue_form.dart, lib/screens/gh_issues.dart, lib/screens/gh_object.dart, lib/screens/gh_pulls.dart, lib/screens/gh_repo.dart, lib/screens/gh_search.dart, lib/screens/gh_trending.dart, lib/screens/gh_user.dart, lib/screens/gh_user_organization.dart, lib/widgets/avatar.dart, lib/widgets/event_item.dart, lib/widgets/notification_item.dart, lib/widgets/repository_item.dart, lib/widgets/user_item.dart, lib/widgets/user_name.dart
Hi @pd4d10,
- In `gh_compare.dart` I removed a `print` statement used while debugging
- In some files, I removed unused imports
- In `avatar.dart` I noticed the `/gitlab` prefix was missing
- Everything else, involves the addition of `/github` prefix
- I used the app for a while and everything seems fine. Hopefully, I haven't missed anything. Maybe you could take a look as well.
Fixes #88
=> chore: github prefix for routes

lib/models/github.dart, lib/models/github.g.dart, lib/router.dart, lib/screens/gh_gist_object.dart, lib/screens/gh_gists.dart, lib/screens/gh_gists_files.dart, lib/screens/gh_user.dart, lib/widgets/gists_item.dart
#80 
- I was not sure how to name the URL for gists. 
- I haven't added a route for blob view of files yet.
=> feat: gists screen

linux/.gitignore, linux/CMakeLists.txt, linux/flutter/CMakeLists.txt, linux/flutter/generated_plugins.cmake, linux/main.cc, linux/my_application.cc, linux/my_application.h
Generated with the latest master:
```
$ flutter --version
Flutter 1.26.0-2.0.pre.157 • channel master • git@github.com:flutter/flutter.git
Framework • revision 4b83be6c23 (7 hours ago) • 2020-12-30 02:09:03 -0500
Engine • revision 0e5a25d779
Tools • Dart 2.12.0 (build 2.12.0-179.0.dev)
```
=> Add generated runner for Linux

CONTRIBUTING.md
Oops sorry just realised I should've added a commit to #137 instead of opening another PR
=> update readme: instructions for i18n

lib/app.dart
=> fix: fallback language

lib/models/gitee.dart, lib/models/gitee.g.dart, lib/screens/ge_search.dart, lib/widgets/issue_item.dart
- Search Screen [`Repositories`, `Users`, `Issues`]
- Fixed overflowing text in `IssueItem`
=> feat: gitee search screen

lib/models/auth.dart, lib/models/bitbucket.dart, lib/models/bitbucket.g.dart, lib/router.dart, lib/screens/bb_issue.dart, lib/screens/bb_issue_comment.dart, lib/screens/bb_issue_form.dart, lib/screens/bb_issues.dart, lib/screens/bb_pulls.dart, lib/screens/bb_repo.dart
Added:
- Create an issue
- Issue Screen
- Comment on Issue
- removed the unnecessary `refs` prop from the uri of `Issues` and `Pulls`
=> bitbucket update

lib/models/gitee.dart, lib/models/gitee.g.dart, lib/router.dart, lib/screens/ge_commit.dart, lib/screens/ge_commits.dart, lib/screens/ge_files.dart, lib/screens/ge_issue_comment.dart, lib/screens/ge_pull.dart, lib/screens/ge_pulls.dart, lib/screens/gh_compare.dart, lib/widgets/files_item.dart
- `Pull Screen` + commenting in pull screen + list of commits
- Reused `ge_issue_comement` for pull request commenting
- The commits in `Pull Screen` link to the `Commit Screen`
- `Files Screen` 
- removed the prop `changes` from `files_item.dart` as it was not being used
- `Commit Screen` 
- Screenshots:
=> gitee updates

lib/models/auth.dart, lib/models/gitee.dart, lib/models/gitee.g.dart, lib/router.dart, lib/screens/ge_commit.dart, lib/screens/ge_issue.dart, lib/screens/ge_issue_comment.dart, lib/screens/ge_issue_form.dart, lib/screens/ge_pull.dart, lib/widgets/action_button.dart, lib/widgets/comment_item.dart
- `Edit` and `Delete` actions in comments of `Issues` and `Pull Requests`
- Update `ActionButton` to use icons 
- `CommentItem` has a prop `commentActionItemList`.  (TODO: for services except gitee)
- minor fix: removed a `print` statement from `GeCommit`
- added `PATCH` and `DELETE` HTTP request types. Refactored `fetchGitee`and added prop `requestType`
- _**`ge_issue_comment` looks a bit cluttered with the `if` statements. I'm not sure how to refactor and make it look cleaner. Any help is appreciated. Thanks.**_
- added `textController`to `ge_issue_comment`. Easier to deal with updation of a comment
_(Just saw that Github markdown supports video as well. Wanted to see how it looks. Hence the video below (also easier instead of copy-pasting multiple screenshots))_ …
=> feat: comment actions (issue/PR)

fastlane/metadata/android/en-US/full_description.txt, fastlane/metadata/android/en-US/short_description.txt
If this is ok, I'll add Simplified Chinese translation later. (Oh, I forgot that you can also speak Chinese :joy:.) Could you please add some screenshots as [this](https://github.com/Webierta/siete_media/tree/master/fastlane/metadata/android/en-US/images)?
=> Add fastlane

lib/models/gitee.dart, lib/models/gitee.g.dart, lib/models/theme.dart, lib/router.dart, lib/screens/ge_commits.dart, lib/screens/ge_contributors.dart, lib/screens/ge_issues.dart, lib/screens/ge_pulls.dart, lib/screens/ge_repo.dart, lib/screens/ge_search.dart
- Labels (in Issues and Pulls Screens)
- Contributors in RepoScreen (contributors response does not have avatar and login objects, hence did not re-use the `contrubution_item` widget 
- fixed the bio in search
- update showPicker to include confirm and cancel buttons
- Fixed #152 
Branch screenshot:
=> feat(gitee): branches, labels, contributors, refactor(RouterScreen)

android/gradle.properties, lib/models/auth.dart, lib/models/gitea.dart, lib/models/gitea.g.dart, lib/router.dart, lib/screens/ge_issue_comment.dart, lib/screens/gt_issue.dart, lib/screens/gt_issue_comment.dart, lib/screens/gt_issue_form.dart, lib/screens/gt_issues.dart
- issue, issueAdd, issueComment, labels
- refactor GeIssueComment
- PR endpoints is still under development by Gitea. files, comments, commits data are missing. Hence I didn't add PR screen,Single Commit Screen. For commit screen too - no API for files of a commit.  
- refactor fetchGitea to handle different HTTP request types
=> feat(Gitea): issue, issueComment, labels, refactor(GeIssueComment)

lib/screens/login.dart
=> add: codeberg login note

lib/home.dart, lib/main.dart, lib/models/auth.dart, lib/models/gogs.dart, lib/models/gogs.g.dart, lib/router.dart, lib/screens/go_commits.dart, lib/screens/go_issues.dart, lib/screens/go_object.dart, lib/screens/go_orgs.dart, lib/screens/go_repo.dart, lib/screens/go_repos.dart, lib/screens/go_search.dart, lib/screens/go_user.dart, lib/screens/go_users.dart, lib/screens/login.dart, lib/widgets/repository_item.dart, lib/widgets/user_item.dart
#117 
- User
- Repo, Repos
- Commits
- Object
- Issues
- Search Screen (placeholder text)
- TODO:  for now `fetchGogs` uses the template of bitbucket. Will refactor when I refactor that
- Lot of attributes were missing in the API response. API seems to be in very early stages. I added comments to indicate this wherever appropriate
- In some places I used this `name: p.fullName.split('/')[1]`. I'm not sure whether I should perform the processing while building the widget or create a getter in `gogs.dart` and move this there?
- Screenshots:
=> feat(gogs): setup

lib/widgets/contribution.dart
Fixes #37 
Hiding the scrollbar seemed the best way to do it
=> fix: hide contribution graph scrollbar

lib/widgets/release_item.dart
Fixes #181 
Added `Card` parent to `ExpansionTile`. Looks better also. Screenshots:
=> fix: github release screen error

lib/screens/gh_compare.dart
=> fix(github): files screen error

lib/app.dart, lib/models/theme.dart, lib/screens/settings.dart, lib/utils/utils.dart
=> feat: choose locale in settings

lib/screens/bb_pulls.dart
Fixed bitbucket pull requests detail page URL
=> fix(bitbucket): pull requests url

lib/widgets/timeline_item.dart
=> fix(github): request review event

lib/screens/settings.dart
- fixed repetition 
- spacing error in tableview (see extra space below in "submit an issue") (just needed to add `hasIcon: false`)
=> fix: settings screen repetition
